### ISSUE TITLE
PackerSync fails on a fresh install

### ISSUE THREAD

**Issue by MarcPaquette** [luan/nvim#71]
PackerSync commands fails on a brand new install before anything's been opened. PackerSync command comes [from the Packer docks](https://github.com/wbthomason/packer.nvim/blob/master/README.md?plain=1#L251)

Reproduction steps below:
```bash
clone_if_not_exist "https://github.com/luan/nvim.git" "${HOME}/.config/nvim"
git clone https://github.com/fatih/vim-go.git ~/.local/share/nvim/site/pack/plugins/start/vim-go
# Add custom Nvim config
echo "Symlinking nvim config"
rm -f "${HOME}/.config/nvim/lua/user/after.lua" "${HOME}/.config/nvim/lua/user/plugins.lua" "${HOME}/.config/nvim/lua/user/before.lua"
mkdir -p "${HOME}"/.config/nvim/lua/user
ln -sf "${DIR}/nvim-after.lua" "${HOME}/.config/nvim/lua/user/after.lua"
ln -sf "${DIR}/nvim-plugins.lua" "${HOME}/.config/nvim/lua/user/plugins.lua"
ln -sf "${DIR}/nvim-before.lua" "${HOME}/.config/nvim/lua/user/before.lua"

nvim +GoInstallBinaries +qall
nvim +UpdateRemotePlugins +qall
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```
Results:
```
+ nvim --headless -c 'autocmd User PackerComplete quitall' -c PackerSync
/home/pivotal/workspace/devenv/configure.sh: line 28: 49115 Segmentation fault      (core dumped) nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```

a follow up run yields:
```
user@machine:~/workspace/environment$ nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
[packer.nvim] [ERROR 16:04:33] a...:lua"]:1: module 'cmp' not found:[packer.nvim] ^Ino field package.preload['cmp'][packer.nvim] ^Ino file './cmp.lua'[packer.nvim] ^Ino file '/usr/share/luajit-2.1.0-beta3/cmp.lua'[packer.nvim] ^Ino file '/usr/local/share/lua/5.1/cmp.lua'[packer.nvim] ^Ino file '/usr/local/share/lua/5.1/cmp/init.lua'[packer.nvim] ^Ino file '/usr/share/lua/5.1/cmp.lua'[packer.nvim] ^Ino file '/usr/share/lua/5.1/cmp/init.lua'[packer.nvim] ^Ino file './cmp.so'[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/cmp.so'[packer.nvim] ^Ino file '/usr/lib/x86_64-linux-gnu/lua/5.1/cmp.so'[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/loadall.so'All parsers are up-to-date!remote/host: python3 host registered plugins ['semshi']remote/host: generated rplugin m...tal/.local/share/nvim/rplugin.vim
```

nvim version info:
```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-PzR5es/neovim-0.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-PzR5es/neovim-0.5.1/build/config -I/build/neovim-PzR5es/neovim-0.5.1/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-PzR5es/neovim-0.5.1/build/src/nvim/auto -I/build/neovim-PzR5es/neovim-0.5.1/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by MarcPaquette** [comment]
Analysis of the core dump if it helps (Probably not):
```
(No debugging symbols found in /usr/bin/nvim)
[New LWP 49179]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nvim --headless -c autocmd User PackerComplete quitall -c PackerSync'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f542cdf3e12 in ?? () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
(gdb) bt
#0  0x00007f542cdf3e12 in ?? () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#1  0x00007f542cdf5b66 in ?? () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#2  0x00007f542ce434a4 in lua_pcall () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#3  0x000055f58059ff8b in ?? ()
#4  0x00007f542d064039 in uv.run_check () from /lib/x86_64-linux-gnu/libuv.so.1
#5  0x00007f542d05d854 in uv_run () from /lib/x86_64-linux-gnu/libuv.so.1
#6  0x000055f58060d809 in loop_poll_events ()
#7  0x000055f580538c0a in os_breakcheck ()
#8  0x000055f58050f7c2 in ?? ()
#9  0x000055f58051194f in ?? ()
#10 0x000055f580511dbd in ?? ()
#11 0x000055f5805121e6 in ?? ()
#12 0x000055f58050baa4 in ?? ()
#13 0x000055f58053d424 in ?? ()
#14 0x000055f58053e9c6 in gen_expand_wildcards ()
#15 0x000055f5805c88c0 in delete_recursive ()
#16 0x000055f5805c8931 in delete_recursive ()
#17 0x000055f5805c8931 in delete_recursive ()
#18 0x000055f58062eb66 in ?? ()
#19 0x000055f580616fce in call_func ()
#20 0x000055f58059f8c7 in nlua_call ()
#21 0x00007f542cdf4fb7 in ?? () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#22 0x00007f542cdf5b66 in ?? () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#23 0x00007f542ce434a4 in lua_pcall () from /lib/x86_64-linux-gnu/libluajit-5.1.so.2
#24 0x000055f5805a1dc4 in ?? ()
#25 0x000055f5804bf268 in state_handle_k_event ()
#26 0x000055f58055d625 in ?? ()
#27 0x000055f58056b2d1 in ?? ()
#28 0x000055f5804bf300 in state_enter ()
#29 0x000055f58056caaf in normal_enter ()
#30 0x000055f58046419f in main ()
```
